version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  install-node-dependencies:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: node:10.16.0-stretch
      # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      # - image: mysql:5.7.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-install-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install NPM dependencies.
          command: npm install
      - save_cache:
          key: npm-install-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  compile-assets:
    docker:
      - image: node:10.16.0-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-install-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Create .env file and set values
          command: |
            cat > .env \<< EOL
            API_HEALTHCHECK_ROUTE="/health-check"
            API_PORT=80
            API_ROUTE_PREFIX="/api"
            EOL
      - run:
          name: Compile assets
          command: |
            npm run ${CIRCLE_BRANCH}:webpack:build
      - run:
          name: Remove the `node_modules` directory.
          command: rm -rf node_modules
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          root: ./dist
          # Must be relative path from root.
          paths:
            - ./

  sync-assets-to-s3:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory.
          at: ./dist
      - run:
          name: "Set an environment variable ($CIRCLE_PROJECT_REPONAME_LOWERCASE)"
          command: |
            set -x
            echo 'export CIRCLE_PROJECT_REPONAME_LOWERCASE=$(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')' >> $BASH_ENV
      - aws-s3/sync:
          aws-region: AWS_DEFAULT_REGION
          from: dist
          to: "s3://${CIRCLE_PROJECT_REPONAME_LOWERCASE}-${CIRCLE_BRANCH}"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  main-workflow:
    jobs:
      - install-node-dependencies

      - compile-assets:
          requires:
            - install-node-dependencies

      - sync-assets-to-s3:
          context: "org-global"
          filters:
            branches:
              only:
                - dev
                - prod
          requires:
            - install-node-dependencies
            - compile-assets
